export const expertiseOptions = [
  "Courtier hypothécaire",
  "Courtier immobilier",
  "Notaire",
  "Constructeur",
  "Évaluateur agréé",
  "Inspecteur en bâtiment",
  "Entrepreneur général",
  "Spécialiste en métiers de la construction et de l'immobilier",
  "Comptable CPA spécialisé en immobilier",
  "Avocat fiscaliste immobilier",
  "Conseiller en sécurité financière immobilier",
  "Architecte",
  "Urbaniste",
  "Gestionnaire de copropriété",
  "Développeur immobilier",
  "Expert en financement immobilier",
  "Consultant en investissement immobilier",
  "Courtier en prêts hypothécaires",
  "Géomètre",
  "Gestionnaire immobilier",
  "Entreprise de déménagement",
  "Autre (préciser)"
];


export const coverageZones = [
  "Canada",
  "Alberta",
  "Colombie-Britannique",
  "Île-du-Prince-Édouard",
  "Manitoba",
  "Nouveau-Brunswick",
  "Nouvelle-Écosse",
  "Nunavut",
  "Ontario",
  "Québec",
  "Saskatchewan",
  "Terre-Neuve-et-Labrador",
  "Territoires du Nord-Ouest",
  "Yukon",
  "Whitehorse",
  "Banff",
  "Toronto",
  "Montréal",
  "Vancouver",
  "Winnipeg",
  "Ottawa",
  "Halifax",
  "Charlottetown"
];


export const languages = [
  "Français",
  "Anglais",
  "Créole",
  "Wolof",
  "Lingala",
  "Dumois",
  "Swahili",
  "Bambara",
  "Yoruba",
  "Hausa",
  "Twi",
  "Igbo",
  "Ewé",
  "Fon",
  "Kikongo",
  "Mandinka",
  "Zulu",
  "Xhosa",
  "Sesotho",
  "Fula",
  "Shona",
  "Krio",
  "Garifuna",
  "Papiamento",
  "Saramaccan",
  "Maroon Creole",
];

